# Generated by Django 5.2 on 2025-05-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='host',
        ),
        migrations.AddField(
            model_name='event',
            name='department',
            field=models.CharField(default='Student Affairs', max_length=100),
        ),
    ]
